#!/usr/bin/env bash

 n=$(( RANDOM % 5 ))

 if [[ n -eq 4 ]]; then
    echo "Something went wrong"
    >&2 echo "The error was using magic numbers"
    exit 6
    #return 1
 fi

 echo "Everything went according to plan"
